name: hercules
description: Hercules

version: 1.0.1+1

environment:
  sdk: ">=2.12.0 <3.0.0"

publish_to: none

dependencies:
  cupertino_icons: any
  device_info_plus: any
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_mobx: any
  flutter_svg: any
  get_it: any
  hive: any
  mobx: any
  openapi:
    path: ./openapi
  package_info: any
  path_provider: any

dev_dependencies:
  build_runner: any
  effective_dart: any
  flutter_launcher_icons: any
  flutter_test:
    sdk: flutter
  hive_generator: any
  mobx_codegen: any
  test: any

flutter_icons:
  ios: true
  android: true
  image_path: assets/icons/ios_icon_raw.png

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/demo_data/
    - assets/icons/

flutter_intl:
  main_locale: en
  enabled: true
  arb_dir: lib/L2_app/l10n # Optional. Sets the directory of your ARB resource files. Provided value should be a valid path on your system. Default: lib/l10n
  output_dir: lib/L2_app/l10n/generated # Optional. Sets the directory of generated localization files. Provided value should be a valid path on your system. Default: lib/generated
