name: hercules
description: Hercules

version: 1.0.251+251

environment:
  sdk: ">=2.17.0 <3.0.0"

publish_to: none

dependencies:
  cupertino_icons: any
  device_info_plus: any
  dropdown_button2: any
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_mobx: any
  get_it: any
  hive: any
  mobx: any
  openapi:
    path: ./openapi
  package_info_plus: any
  path_provider: any

dev_dependencies:
  build_runner: any
  effective_dart: any
  flutter_launcher_icons: any
  flutter_test:
    sdk: flutter
  hive_generator: any
  mobx_codegen: any
  test: any

flutter_icons:
  ios: true
  android: true
  image_path: scripts/ios_icon_raw.png

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/ca/
    - assets/fonts/
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-T.ttf
          weight: 100
        - asset: assets/fonts/Roboto-TI.ttf
          weight: 100
          style: italic
        - asset: assets/fonts/Roboto-L.ttf
          weight: 300
        - asset: assets/fonts/Roboto-LI.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/Roboto-R.ttf
          weight: 400
        - asset: assets/fonts/Roboto-RI.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/Roboto-M.ttf
          weight: 500
        - asset: assets/fonts/Roboto-MI.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Roboto-B.ttf
          weight: 700
        - asset: assets/fonts/Roboto-BI.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/Roboto-BL.ttf
          weight: 900
        - asset: assets/fonts/Roboto-BLI.ttf
          weight: 900
          style: italic

flutter_intl:
  main_locale: en
  enabled: true
  arb_dir: lib/L3_app/l10n # Optional. Sets the directory of your ARB resource files. Provided value should be a valid path on your system. Default: lib/l10n
  output_dir: lib/L3_app/l10n/generated # Optional. Sets the directory of generated localization files. Provided value should be a valid path on your system. Default: lib/generated
