name: avanplan
description: Avanplan

version: 2.11.2923+2923

environment:
  sdk: ">=3.1.0 <4.0.0"

publish_to: none

dependencies:
  app_settings: any
  built_collection: any
  collection: any
  crypto: any
  cupertino_icons: any
  device_info_plus: any
  dio: any
  file_selector: any
  firebase_core: any
  firebase_messaging: any
  flutter:
    sdk: flutter
  flutter_dotenv: any
  flutter_localizations:
    sdk: flutter
  flutter_mobx: any
  flutter_slidable: any
  get_it: any
  go_router: any
  google_sign_in: ^5.4.4
  hive: any
  image_picker: any
  in_app_purchase: any
  intl: any
  mobx: any
  avanplan_api:
    path: ./openapi/avanplan_api
  package_info_plus: ^8.0.0
  path_provider: any
  share_plus: any
  sign_in_with_apple: any
  url_launcher: any
  webview_flutter: any

dev_dependencies:
  build_runner: any

  flutter_launcher_icons: any
  flutter_lints: any
  flutter_native_splash: any
  hive_generator: any
  intl_utils: any
  mobx_codegen: any

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/ca/
    - assets/fonts/
    - assets/icons/
    - assets/images/
  fonts:
    - family: MontserratAvanplan
      fonts:
        - asset: assets/fonts/Montserrat-R.ttf
          weight: 400
        - asset: assets/fonts/Montserrat-M.ttf
          weight: 500
        - asset: assets/fonts/Montserrat-B.ttf
          weight: 700
    - family: ComfortaaAvanplan
      fonts:
        - asset: assets/fonts/Comfortaa-SB.ttf
          weight: 600
    - family: RobotoAvanplan
      fonts:
        - asset: assets/fonts/Roboto-L.ttf
          weight: 300
        - asset: assets/fonts/Roboto-R.ttf
          weight: 400
        - asset: assets/fonts/Roboto-M.ttf
          weight: 500

# dart run flutter_launcher_icons
flutter_launcher_icons:
  ios: true
  android: true
  web:
    generate: true
  image_path: scripts/ios_icon_raw.png

flutter_intl:
  main_locale: en
  enabled: true
  arb_dir: lib/L3_app/l10n # Optional. Default: lib/l10n
  output_dir: lib/L3_app/l10n/generated # Optional. Default: lib/generated

# https://pub.dev/packages/flutter_native_splash:
# dart run flutter_native_splash:create
# Исходная картинка должна быть @4x
# после запуска команды вручную заменить все измененные изображения, т.к. очень плохо ресайзит, размер больших больше, а мелкие - лесенкой все
flutter_native_splash:
  color: "#F4F5F7"
  color_dark: "#24262E"
  image: scripts/launch_image.png
  image_dark: scripts/launch_image_dark.png