name: avanplan
description: Avanplan

version: 1.12.1821+1821

environment:
  sdk: ">=3.1.0 <4.0.0"

publish_to: none

dependencies:
  app_settings: any
  cupertino_icons: any
  device_info_plus: ^9.0.2
  drag_and_drop_lists: any
  firebase_messaging: ^14.7.4
  flutter:
    sdk: flutter
  flutter_dotenv: any
  flutter_linkify: any
  flutter_localizations:
    sdk: flutter
  flutter_mobx: any
  get_it: any
  google_sign_in: ^5.4.4
  hive: any
  in_app_purchase: ^3.1.5
  mobx: any
  openapi:
    path: ./openapi
  package_info_plus: any
  path_provider: any
  share_plus: ^7.0.2
  sign_in_with_apple: any
  url_launcher: any

dev_dependencies:
  build_runner: any
  flutter_launcher_icons: any
  flutter_native_splash: any
  flutter_test:
    sdk: flutter
  hive_generator: any
  intl_utils: any
  lints: any
  mobx_codegen: any
  test: any

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/ca/
    - assets/fonts/
    - assets/icons/
    - assets/images/
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-M.ttf
          weight: 500
        - asset: assets/fonts/Montserrat-B.ttf
          weight: 700
    - family: Comfortaa
      fonts:
        - asset: assets/fonts/Comfortaa-SB.ttf
          weight: 600
    - family: RobotoAvanplan
      fonts:
        - asset: assets/fonts/Roboto-L.ttf
          weight: 300
        - asset: assets/fonts/Roboto-R.ttf
          weight: 400
        - asset: assets/fonts/Roboto-M.ttf
          weight: 500

# dart run flutter_launcher_icons
flutter_launcher_icons:
  ios: true
  android: true
  web:
    generate: true
  image_path: scripts/ios_icon_raw.png

flutter_intl:
  main_locale: en
  enabled: true
  arb_dir: lib/L3_app/l10n # Optional. Default: lib/l10n
  output_dir: lib/L3_app/l10n/generated # Optional. Default: lib/generated

# https://pub.dev/packages/flutter_native_splash:
# dart run flutter_native_splash:create
# Исходная картинка должна быть @4x
# после запуска команды вручную заменить все измененные изображения, т.к. очень плохо ресайзит, размер больших больше, а мелкие - лесенкой все
flutter_native_splash:
  color: "#ECEBEA"
  color_dark: "#2C2C34"
  image: scripts/launch_image.png
  image_dark: scripts/launch_image_dark.png