name: avanplan
description: Avanplan

version: 1.0.1035+1035

environment:
  sdk: ">=2.19.0 <3.0.0"

publish_to: none

dependencies:
  cupertino_icons: any
  device_info_plus: ^8.1.0
  flutter:
    sdk: flutter
  flutter_apns_only: any
  flutter_localizations:
    sdk: flutter
  flutter_mobx: any
  font_awesome_flutter: any
  get_it: any
  google_sign_in: ^5.4.4
  hive: any
  mobx: any
  openapi:
    path: ./openapi
  package_info_plus: any
  path_provider: any
  share_plus: ^6.3.1
  sign_in_with_apple: any
  url_launcher: any

dev_dependencies:
  build_runner: any
  flutter_launcher_icons: any
  flutter_test:
    sdk: flutter
  hive_generator: any
  intl_utils: any
  lints: any
  mobx_codegen: any
  test: any

flutter_icons:
  ios: true
  android: true
  image_path: scripts/ios_icon_raw.png

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/ca/
    - assets/fonts/
    - assets/images/
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-T.ttf
          weight: 200
        - asset: assets/fonts/Roboto-L.ttf
          weight: 300
        - asset: assets/fonts/Roboto-R.ttf
          weight: 400
        - asset: assets/fonts/Roboto-M.ttf
          weight: 500

flutter_intl:
  main_locale: en
  enabled: true
  arb_dir: lib/L3_app/l10n # Optional. Default: lib/l10n
  output_dir: lib/L3_app/l10n/generated # Optional. Default: lib/generated
