default_context:
  project_name: 'Hercules'
  project_slug: 'hercules'
  domain_main: 'hercules.com'
  domain_staging: 'stag.hercules.com'
  docker_swarm_stack_name_main: 'hercules-com'
  docker_swarm_stack_name_staging: 'stag-hercules-com'
  secret_key: '4f99074587960da900b91ef38c338679cdf030692e1d1bd8797123ab379fcdef'
  first_superuser: 'admin@hercules.com'
  first_superuser_password: 'admin'
  backend_cors_origins: '["http://localhost", "http://localhost:4200", "http://localhost:3000", "http://localhost:8080", "https://localhost", "https://localhost:4200", "https://localhost:3000", "https://localhost:8080", "http://dev.hercules.com", "https://stag.hercules.com", "https://hercules.com", "http://local.dockertoolbox.tiangolo.com", "http://localhost.tiangolo.com"]'
  smtp_port: '587'
  smtp_host: ''
  smtp_user: ''
  smtp_password: ''
  smtp_emails_from_email: 'info@hercules.com'
  postgres_password: 'hercules'
  pgadmin_default_user: 'hercules'
  pgadmin_default_user_password: 'hercules'
  traefik_constraint_tag: 'hercules.com'
  traefik_constraint_tag_staging: 'stag.hercules.com'
  traefik_public_constraint_tag: 'traefik-public'
  flower_auth: 'admin:admin'
  sentry_dsn: ''
  docker_image_prefix: ''
  docker_image_backend: 'backend'
  docker_image_celeryworker: 'celeryworker'
  docker_image_frontend: 'frontend'
  _copy_without_render: [frontend/src/**/*.html, frontend/src/**/*.vue, frontend/node_modules/*, backend/app/app/email-templates/**]
  _template: ./
