"""empty message

Revision ID: 5eb94a3cef8a
Revises: afa54314d09a
Create Date: 2022-02-28 00:50:26.274940

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "5eb94a3cef8a"
down_revision = "afa54314d09a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("goals", sa.Column("remote_parent_id", sa.Integer(), nullable=True))
    op.add_column("milestones", sa.Column("remote_parent_id", sa.Integer(), nullable=True))
    op.add_column("persons", sa.Column("remote_parent_id", sa.Integer(), nullable=True))
    op.add_column("tasks", sa.Column("remote_parent_id", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("tasks", "remote_parent_id")
    op.drop_column("persons", "remote_parent_id")
    op.drop_column("milestones", "remote_parent_id")
    op.drop_column("goals", "remote_parent_id")
    # ### end Alembic commands ###
