"""empty message

Revision ID: 927ca44edf4e
Revises: 
Create Date: 2022-04-20 00:44:39.184397

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "927ca44edf4e"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "goalstatuss",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("closed", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("title"),
    )
    op.create_index(op.f("ix_goalstatuss_id"), "goalstatuss", ["id"], unique=False)
    op.create_table(
        "persons",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("firstname", sa.String(), nullable=True),
        sa.Column("lastname", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_persons_email"), "persons", ["email"], unique=True)
    op.create_index(op.f("ix_persons_id"), "persons", ["id"], unique=False)
    op.create_table(
        "remotetrackertypes",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("title"),
    )
    op.create_index(op.f("ix_remotetrackertypes_id"), "remotetrackertypes", ["id"], unique=False)
    op.create_table(
        "taskprioritys",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("order", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("title"),
    )
    op.create_index(op.f("ix_taskprioritys_id"), "taskprioritys", ["id"], unique=False)
    op.create_table(
        "taskstatuss",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("closed", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("title"),
    )
    op.create_index(op.f("ix_taskstatuss_id"), "taskstatuss", ["id"], unique=False)
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("password", sa.String(), nullable=False),
        sa.Column("full_name", sa.String(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.Column("is_superuser", sa.Boolean(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_index(op.f("ix_users_full_name"), "users", ["full_name"], unique=False)
    op.create_index(op.f("ix_users_id"), "users", ["id"], unique=False)
    op.create_table(
        "remotetrackers",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("remote_tracker_type_id", sa.Integer(), nullable=True),
        sa.Column("url", sa.String(), nullable=False),
        sa.Column("login_key", sa.String(), nullable=False),
        sa.Column("password", sa.String(), nullable=True),
        sa.Column("description", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["remote_tracker_type_id"],
            ["remotetrackertypes.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_remotetrackers_id"), "remotetrackers", ["id"], unique=False)
    op.create_table(
        "goals",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("created_on", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_on", sa.DateTime(timezone=True), nullable=False),
        sa.Column("due_date", sa.DateTime(timezone=True), nullable=True),
        sa.Column("closed", sa.Boolean(), nullable=False),
        sa.Column("remote_code", sa.String(), nullable=True),
        sa.Column("parent_id", sa.Integer(), nullable=True),
        sa.Column("status_id", sa.Integer(), nullable=True),
        sa.Column("assignee_id", sa.Integer(), nullable=True),
        sa.Column("author_id", sa.Integer(), nullable=True),
        sa.Column("remote_tracker_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["assignee_id"],
            ["persons.id"],
        ),
        sa.ForeignKeyConstraint(
            ["author_id"],
            ["persons.id"],
        ),
        sa.ForeignKeyConstraint(["parent_id"], ["goals.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["remote_tracker_id"], ["remotetrackers.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(
            ["status_id"],
            ["goalstatuss.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_goals_id"), "goals", ["id"], unique=False)
    op.create_table(
        "tasks",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("created_on", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_on", sa.DateTime(timezone=True), nullable=False),
        sa.Column("due_date", sa.DateTime(timezone=True), nullable=True),
        sa.Column("closed", sa.Boolean(), nullable=False),
        sa.Column("remote_code", sa.String(), nullable=True),
        sa.Column("parent_id", sa.Integer(), nullable=True),
        sa.Column("goal_id", sa.Integer(), nullable=False),
        sa.Column("status_id", sa.Integer(), nullable=True),
        sa.Column("priority_id", sa.Integer(), nullable=True),
        sa.Column("assignee_id", sa.Integer(), nullable=True),
        sa.Column("author_id", sa.Integer(), nullable=True),
        sa.Column("remote_tracker_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["assignee_id"],
            ["persons.id"],
        ),
        sa.ForeignKeyConstraint(
            ["author_id"],
            ["persons.id"],
        ),
        sa.ForeignKeyConstraint(["goal_id"], ["goals.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["parent_id"], ["tasks.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["priority_id"],
            ["taskprioritys.id"],
        ),
        sa.ForeignKeyConstraint(["remote_tracker_id"], ["remotetrackers.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(
            ["status_id"],
            ["taskstatuss.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_tasks_id"), "tasks", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_tasks_id"), table_name="tasks")
    op.drop_table("tasks")
    op.drop_index(op.f("ix_goals_id"), table_name="goals")
    op.drop_table("goals")
    op.drop_index(op.f("ix_remotetrackers_id"), table_name="remotetrackers")
    op.drop_table("remotetrackers")
    op.drop_index(op.f("ix_users_id"), table_name="users")
    op.drop_index(op.f("ix_users_full_name"), table_name="users")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    op.drop_index(op.f("ix_taskstatuss_id"), table_name="taskstatuss")
    op.drop_table("taskstatuss")
    op.drop_index(op.f("ix_taskprioritys_id"), table_name="taskprioritys")
    op.drop_table("taskprioritys")
    op.drop_index(op.f("ix_remotetrackertypes_id"), table_name="remotetrackertypes")
    op.drop_table("remotetrackertypes")
    op.drop_index(op.f("ix_persons_id"), table_name="persons")
    op.drop_index(op.f("ix_persons_email"), table_name="persons")
    op.drop_table("persons")
    op.drop_index(op.f("ix_goalstatuss_id"), table_name="goalstatuss")
    op.drop_table("goalstatuss")
    # ### end Alembic commands ###
