"""empty message

Revision ID: 84ad156c7ac6
Revises: 
Create Date: 2022-04-24 21:47:10.801550

"""
#  Copyright (c) 2022. Alexandr Moroz

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "84ad156c7ac6"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "auth",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("password", sa.String(), nullable=False),
        sa.Column("full_name", sa.String(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.Column("is_superuser", sa.Boolean(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_email"), "auth", ["email"], unique=True)
    op.create_index(op.f("ix_users_full_name"), "auth", ["full_name"], unique=False)
    op.create_index(op.f("ix_users_id"), "auth", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_users_id"), table_name="auth")
    op.drop_index(op.f("ix_users_full_name"), table_name="auth")
    op.drop_index(op.f("ix_users_email"), table_name="auth")
    op.drop_table("auth")
    # ### end Alembic commands ###
